name: travel_guide
description: "Final version"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  url_launcher: ^6.3.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2
  image_picker: ^0.8.7+3


  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/